### ISSUE TITLE
Landing Page Slider

### ISSUE THREAD

**Issue by jasonnchann24** [jasonnchann24/bloomwood-project#68]
Case : 
 - landing page banner only support single photo

To do:
- [x] Backend to handle multiple  #69 
- [x] CMS to CRUD images #69 
- [x] FE to show those images #69
